name: Code Questioning workflow

on:
  push:
    branches:
      - main  # 필요한 브랜치 이름을 설정하세요.

jobs:
  diff-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get the recent commit author
      run: |
        commit_sha=${{ github.event.after }}
        echo "Commit SHA: $commit_sha"
        author=$(git log -1 --format="%an <%ae>" $commit_sha)
        echo "author=$author" >> $GITHUB_ENV
        
    # Display the author for debugging purposes
    - name: Display Author
      run: echo ${{ env.author }}

    - name: save to diff.txt
      run: |
        git fetch origin ${{ github.event.before }} ${{ github.event.after }} # 이전 커밋과 현재 커밋 가져오기
        git diff ${{ github.event.before }} ${{ github.event.after }} | grep '^+[^+]' | sed 's/^+//' > diff.txt # 변경 사항 중 추가된 내용만을 가져와 txt 생성
        cat diff.txt

    - name: Create payload.json
      run: |
        diff=$(cat diff.txt | jq -Rs .) # diff.txt를 josn 형식의 값으로 변환
        echo "{\"author\": \"${{ env.author }}\", \"diff\": $diff}" > payload.json # author와 diff를 json 확장자로 변환
        cat payload.json

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Invoke Lambda function
      run: |
        aws lambda invoke \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --cli-binary-format raw-in-base64-out \
          --payload file://payload.json \
          response.json
        cat response.json
