name: Log Changed Code

on:
  push:
    branches:
      - main  # 필요한 브랜치 이름을 설정하세요. 모든 브랜치에 대해 실행하려면 이 줄을 제거하세요.

jobs:
  log-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get the previous commit SHA
      id: prev-commit
      run: echo "::set-output name=sha::$(git rev-parse HEAD~1)"

    - name: Get the current commit SHA
      id: curr-commit
      run: echo "::set-output name=sha::$(git rev-parse HEAD)"

    - name: Display the commit SHAs
      run: |
        echo "Previous commit SHA: ${{ steps.prev-commit.outputs.sha }}"
        echo "Current commit SHA: ${{ steps.curr-commit.outputs.sha }}"

    - name: Log changes
      run: |
        git diff ${{ steps.prev-commit.outputs.sha }} ${{ steps.curr-commit.outputs.sha }} --unified=0
