name: Diff Push Changes

on:
  push:
    branches:
      - main  # 필요한 브랜치 이름을 설정하세요.

jobs:
  diff-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display commit range
      run: |
        echo "Commit range: ${{ github.event.before }}..${{ github.event.after }}"
    
    - name: Get the recent commit author
      run: |
        commit_sha=${{ github.event.after }}
        echo "Commit SHA: $commit_sha"
        author=$(git log -1 --format="%an <%ae>" $commit_sha)
        echo "Author: $author"
        echo "AUTHOR_NAME=$author" >> $GITHUB_ENV
    
    - name: Show diff and save to environment variable
      id: diff
      run: |
        git fetch origin ${{ github.event.before }} ${{ github.event.after }}
        diff_output=$(git diff ${{ github.event.before }} ${{ github.event.after }} | grep '^+[^+]' | sed 's/"/\\"/g' | tr '\n' ' ')
        echo "DIFF_OUTPUT=$diff_output" >> $GITHUB_ENV

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Create JSON payload
      run: |
        echo '{"author": "' ${{ env.AUTHOR_NAME }} '", "diff": "' ${{ env.DIFF_OUTPUT }} '"}' > payload.json
        
    - name: Invoke Lambda function
      run: |
        aws lambda invoke \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --cli-binary-format raw-in-base64-out \
          --payload file://payload.json \
          response.json
        cat response.json
