name: Diff Push Changes

on:
  push:
    branches:
      - main  # 필요한 브랜치 이름을 설정하세요.

jobs:
  diff-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display commit range
      run: |
        echo "Commit range: ${{ github.event.before }}..${{ github.event.after }}"

    - name: Get the recent commit author
      run: |
          commit_sha=${{ github.event.after }}
          echo "Commit SHA: $commit_sha"
          author=$(git log -1 --format="%an <%ae>" $commit_sha)
          echo "Author: $author"
          echo "AUTHOR_NAME=$author" >> $GITHUB_ENV

    - name: Show diff
      run: |
        git fetch origin ${{ github.event.before }} ${{ github.event.after }}
        git diff ${{ github.event.before }} ${{ github.event.after }} | grep '^+[^+]'
