name: Code Questioning workflow

on:
  push:
    branches:
      - main  # 필요한 브랜치 이름을 설정하세요.

jobs:
  diff-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Display commit range
    #   run: |
    #     echo "Commit range: ${{ github.event.before }}..${{ github.event.after }}"

    - name: Get the recent commit author
      run: |
        recent_commit=${{ github.event.after }} # 최근 커밋 가져오기
        echo "Commit SHA: $recent_commit" # 최근 커밋 출력
        # author=$(git log -1 --format="%an <%ae>" $recent_commit) # 최근 커밋에서 author 저장
        author=$(git log -1 --format="%an <%ae>") # 최근 커밋에서 author 저장
        echo "author=$author" >> $GITHUB_ENV # author 출력 후 저장

    - name: Show diff and save to file
      run: |
        git fetch origin ${{ github.event.before }} ${{ github.event.after }}
        git diff ${{ github.event.before }} ${{ github.event.after }} | grep '^+[^+]' | sed 's/^+//' > diff.txt
        cat diff.txt

    - name: Create payload.json
      run: |
        diff=$(cat diff.txt | jq -Rs .)
        echo "{\"author\": \"${{ env.author }}\", \"diff\": $diff}" > payload.json
        cat payload.json

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Invoke Lambda function
      run: |
        aws lambda invoke \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --cli-binary-format raw-in-base64-out \
          --payload file://payload.json \
          response.json
        cat response.json
